version: 6.5.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
environment:
  pfx_decrypt:
    secure: AHimXBh+X6BjzeQqH6XOj+E4njc5S4kxhacPvuR1aK0=
  pfx_pwd:
    secure: 8O5C6ksDG2epfcj92HlPPg==
before_build:
- cmd: >-
    cd src

    nuget restore

    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt dummy.data -secret %pfx_decrypt% -out NFETeam.pfx    
- ps: >-
    Import-PfxCertificate -FilePath C:\mypfx.pfx cert:\localMachine\VS_KEY_05B73E7374811DEA -Password $env:pfx_pwd

    Write-Output "Sucesfully imported $pfx into StrongName CSP store"
build:
  verbosity: minimal
after_build:
- cmd: cd C:\projects\nfirmwareeditor\src\out\
- cmd: del /q *.pdb, *.xml
artifacts:
- path: src\out
  name: NFirmwareEditor-v$(appveyor_build_version)
