version: 6.5.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
environment:
  dummy_secret:
    secure: AHimXBh+X6BjzeQqH6XOj+E4njc5S4kxhacPvuR1aK0=
before_build:
- cmd: >-
    cd src

    nuget restore

    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt dummy.data -secret %dummy_secret% -out NFETeam.snk
build:
  verbosity: minimal
after_build:
- cmd: cd %APPVEYOR_BUILD_FOLDER%\src\out\
- cmd: del /q *.pdb, *.xml
artifacts:
- path: src\out
  name: NFirmwareEditor-v$(APPVEYOR_BUILD_VERSION)
