version: 6.5.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
environment:
  pfx_decrypt:
    secure: AHimXBh+X6BjzeQqH6XOj+E4njc5S4kxhacPvuR1aK0=
  pfx_pwd:
    secure: 8O5C6ksDG2epfcj92HlPPg==
before_build:
  - cmd: cd src
  - cmd: nuget restore
  - cmd: nuget install secure-file -ExcludeVersion
  - cmd: secure-file\tools\secure-file -decrypt dummy.data -secret $env:pfx_decrypt -out NFETeam.pfx
  - ps: $psw = ConvertTo-SecureString $env:pfx_pwd -AsPlainText
  - ps: Import-PfxCertificate -FilePath .\NFETeam.pfx -CertStoreLocation cert:\CurrentUser\My -Password $psw
build:
  verbosity: quiet
after_build:
- cmd: cd C:\projects\nfirmwareeditor\src\out\
- cmd: del /q *.pdb, *.xml
artifacts:
- path: src\out
  name: NFirmwareEditor-v$(appveyor_build_version)